### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by JiDai** [mapbox/store-locator-ios#3]
Hi,

I just tried to run the project but I got an error : `No such module 'MapboxDirections'` after `git clone` and `pod install`
I use Xcode 9.1

**Comment by captainbarbosa** [comment]
Hi @JiDai, are you still seeing this issue?

**Comment by JiDai** [comment]
It is ok now, thanks, all pods has been installed and the project builds : 

```
Installing Mapbox-iOS-SDK (3.7.3)
Installing MapboxDirections.swift (0.15.1)
Installing Polyline (4.2.0)
```
